name: Lint check on push from any branch or to development
  on: push
  jobs:
    build:
      name: Lint Runner
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: lint # will run `yarn lint` command
