name: Pull Request Merge to Development
  on: push
    branches: 
      - development
  jobs:
    build:
      name: Lint Runner
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: lint # will run `yarn lint` command

